[tool.autopep8]
max_line_length = 160
in-place = true
recursive = true
aggressive = 3

[tool.isort]
line_length = 180
force_single_line = true
force_sort_within_sections = true
lexicographical = true
single_line_exclusions = ["typing"]
order_by_type = false
group_by_package = true