name: Main CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: [windows-latest]
    strategy:
      matrix:
        python-version: [
          "3.11"
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Echo something
        run: echo CI builder workflow has been disabled. Release can still be manually triggered.

  # Only perform release when manually triggered and on main branch
  release:
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.github_token}}
      - name: Read VERSION file
        id: getversion
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: v${{ steps.getversion.outputs.version }}.${{ steps.buildnumber.outputs.build_number }}
          tag_exists_error: true
